name: namaadhu_vaguthu
description: Prayer times app for the Maldives.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.2
  csv: ^5.0.1
  shared_preferences: ^2.0.15
  intl: ^0.18.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  ionicons: ^0.2.1
  awesome_notifications: ^0.6.19

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/csv/
    - assets/csv/islands/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
